service: stockmania

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  lambdaHashingVersion: 20201221
  profile: serverless-admin
  stage: dev
  timeout: 20
  environment:
    SESSION_NAME: ${self:service}-${opt:stage, self:provider.stage}

functions:
  getWalletOptions:
    timeout: 10
    memorySize: 512
    handler: src/cei.getWalletOptions
    package:
      patterns:
        - src/cei.js
    events:
    - http:
        path: cei/wallet-options
        method: get
        cors: true
  getWallet:
    timeout: 10
    memorySize: 512
    handler: src/cei.getWallet
    package:
      patterns:
        - src/cei.js
    events:
    - http:
        path: cei/wallet
        method: get
        cors: true
  getStockHistory:
    timeout: 10
    memorySize: 512
    handler: src/cei.getStockHistory
    package:
      patterns:
        - src/cei.js
    events:
    - http:
        path: cei/stock-history
        method: get
        cors: true     
  getStockHistoryOptions:
    timeout: 10
    memorySize: 512
    handler: src/cei.getStockHistoryOptions
    package:
      patterns:
        - src/cei.js
    events:
    - http:
        path: cei/stock-history-options
        method: get
        cors: true    
  getDividends:
    timeout: 10
    memorySize: 512
    handler: src/cei.getDividends
    package:
      patterns:
        - src/cei.js
    events:
    - http:
        path: cei/dividends
        method: get
        cors: true
  getTreasures:
    timeout: 10
    memorySize: 512
    handler: src/cei.getTreasures
    package:
      patterns:
        - src/cei.js
    events:
    - http:
        path: cei/treasures
        method: get
        cors: true